[package]
name = "IOT_Smart_Hub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wio_terminal = { git = "https://github.com/atsamd-rs/atsamd" }
panic-halt = "0.2"

[dev-dependencies]